spring.config.import=optional:file:.env[.properties]

spring.application.name=auth
server.port=${SERVER_PORT}

spring.datasource.url=${URL_BD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




#trading.deriv.symbols= R_50,R_100,R_10,R_25,R_75,CRASH500
trading.deriv.symbols=R_10,1HZ10V,1HZ15V,1HZ25V,R_25,1HZ30V,1HZ50V,R_50,1HZ75V,R_75,1HZ100V,R_100,BOOM300N,BOOM500,BOOM600,BOOM900,BOOM1000,CRASH300N,CRASH500,CRASH600,CRASH900,CRASH1000,JD10,JD25,JD50,JD75,JD100,stpRNG,stpRNG2,stpRNG3,stpRNG4,stpRNG5,frxXAUUSD,frxEURUSD,frxGBPUSD,cryBTCUSD,cryETHUSD

# URLs de l'application (configurer dans .env)
app.backend.url=${APP_BACKEND_URL:http://localhost:8082}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

# OAuth Google
google.client.id=${GOOGLE_CLIENT_ID}
